# send a get request to the products endpoint, using http protocol 1.1
GET http://127.0.0.1:8000/products/ HTTP/1.1

# seperates the requests
###

POST  http://127.0.0.1:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNjE0Nzc4LCJpYXQiOjE3NTE2MTQ0NzgsImp0aSI6Ijg3OWI0YzgyOGUzZTQ4NjZhNWY2NDg3NDMzYmY2ZDQ3IiwidXNlcl9pZCI6MX0.hMYwAQ_1-jYtDYdNHTMAfnUn4KET9HG3hy3TCWKho04

{
    "name": "A New Produce",
    "price": 19.99,
    "stock": 14,
    "description": "A new product for testing purposes."
}


###

POST  http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}

###

GET http://127.0.0.1:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNjE5OTIxLCJpYXQiOjE3NTE2MTk2MjEsImp0aSI6IjMyOGQzYTIzYTY5ZTRiN2ViY2IxMjQwMGM2NmEyMmMzIiwidXNlcl9pZCI6MX0.GTbz4Jq_vFuf4OKIYb41ds_KcnDFNaVfjb3avYfU0io